### PR TITLE
Support for OpenEXR format in cli

### PR DESCRIPTION
**Pull request by Lichtso**
This enables selecting ".pfm" or ".exr" as file format for input and output images in the command line interface.

### CODE REVIEW

**Comment by Lichtso** [comment]
I rebased the commit on the current master branch.
Hope it can be merged now.

**Comment by atafra** [comment]
Open Image Denoise v1.2.0 has now support for OpenEXR and other formats as well through OpenImageIO, so I'm now closing this. Thanks!

**Comment by rlesac** [comment]
Well, it seems the support for exr is gone, I get:
`Error: cannot load unsupported image file format: 'image.exr'`

**Comment by atafra** [comment]
No, EXR support is still present but it was never enabled by default (due to the dependence on OpenImageIO). You need to rebuild OIDN from source, enabling OpenImageIO support in CMake.

**Pull request closed without merging**
