### PR TITLE
Add Bazel Support

### PR DESCRIPTION
**Pull request by Vertexwahn**
Attempt to add Bazel build support.

### CODE REVIEW

**Comment by atafra** [comment]
Sorry but we can't commit to support another build system in addition to CMake.

**Comment by Vertexwahn** [comment]
It's still only a draft - but anyways good to get the feedback this early ;) - will then create `rules_odin` (similar as I did for https://github.com/Vertexwahn/rules_embree)

**Comment by Vertexwahn** [comment]
As promised here are my Bazel rules for oidn: https://github.com/Vertexwahn/rules_oidn/commits/main

**Comment by abebeos** [comment]
> Please note using Bazel you have the advantage that third party dependencies such as ispc are fetched automatically! Magic!

This is not relevant. You need to provide convincing rationales so the team can decide positively about at least including the changes that will allow building with Bazel.

Convince me (a neutral outsider/observer) first, see https://github.com/Vertexwahn/rules_oidn/issues/3

**Pull request closed without merging**
